### ISSUE TITLE
RegionSwitch : LanguageSwitch

### ISSUE THREAD

**Issue by elfalehed** [tunpl/oxycare#1]
in the masterhead you'll find the features section. Based on multiple features each one have its own independent page. 
in pick the region section there are some contradictions since its named "languageSwitch" in the sourcecode. 

Before editing anything please make sure you understand How the layout works and once we can edit some improvements with be in the CONTRIBUTING.md

**Comment by inesChebil** [comment]
for this , why can't we just remove the LanguageSwitch  from Freatures/index.tsx ?

**Comment by elfalehed** [comment]
the language switch is directed to that specific section: radio button based, we can edit the feature and make it a custom one that satisfies our needs. without the bother of creating one from scratch.
