### ISSUE TITLE
The home needs some modifications in my opinion

### ISSUE THREAD

**Issue by inesChebil** [tunpl/oxycare#17]
Hi, 
In my opinion , the home page should look like this: 
![image](https://user-images.githubusercontent.com/44600824/116528932-ad60b600-a8dc-11eb-8321-dadf84114462.png)

without adding the following features:
![image](https://user-images.githubusercontent.com/44600824/116529173-ef89f780-a8dc-11eb-986b-fb6c1539e032.png)
because it it's not good organized (in my opinion :D)

**Comment by inesChebil** [comment]
if the user wants to give , 
we have to add other fields where he can add these infos
![image](https://user-images.githubusercontent.com/44600824/116529977-cc137c80-a8dd-11eb-9788-3e793ecd902f.png)

**Comment by elfalehed** [comment]
seems good, i loved the structure. please submit them in a pull request and I will merge.

**Comment by elfalehed** [comment]
one more thing in the phone number section the violet logo is redux's you need to change that 
in the state.svg file in the current repository copy its code and replace it with the ones you have in your local host right now, before pushing the pull request

**Comment by inesChebil** [comment]
Normally , i have to add git pull origin dev , to get the recent updates, No ? but i got nothing ? nothing changes

**Comment by elfalehed** [comment]
Search in this repository a file called state.svg copy its content and replace it in the state.svg on your machine (local repo)
got it?
