### ISSUE TITLE
add a submit button

### ISSUE THREAD

**Issue by elfalehed** [tunpl/oxycare#8]
add the submit button. after completing the form the submit button will check the status of the text areas since: the phone number is needed, the region is needed as well for this offer to work. Build a submit button with these given requirements to check before actually submitting the response.

**Comment by inesChebil** [comment]
the submit button will be added at the bottom of the page of the home page ?

**Comment by elfalehed** [comment]
Yes. We need to create a function that will check the text /areas and the radio buttons if they're filled or not. In case they're filled the submit function will work otherwise it will throw an error asking the user to fill in the blanks.

**Comment by elfalehed** [comment]
already done.
Just need to create a function to check the text area and the region radio button
